### ISSUE TITLE
MacOS not reading config.yml

### ISSUE THREAD

**Issue by CristolGDM** [Achno/gowall#29]
Hello there

Just to start, I don't think this is a duplicate of https://github.com/Achno/gowall/issues/18 , since I was able to build and use the command

However for some reason I am not able to use the config file

My config file:

```bash
$ cat ~/.config/gowall/config.yml
themes:
  - name: "placeholder1"
    colors:
      - "#000000"
      - "#ef766d"
      - "#88f397"
      - "#f4f8a7"
      - "#c4a9f4"
      - "#aceafb"
      - "#ffffff"
      - "#f297cd"
EnableImagePreviewing: false/
```

If I try to use placeholder1 theme:

```bash
$ gowall convert ~/Pictures/temp.jpg -t placeholder1
Processing single image...
 Error Processing Image: while processing image: unknown theme placeholder1
```

It also keeps opening the image once it's done but I'm not sure if that's supposed to be affected by EnableImagePreviewing

I tried:
- restarting my terminal
- validating the yml
- removing the EnableImagePreviewing line

**Comment by Achno** [comment]
Hey there @CristolGDM ,

First of all some info : 

1) How did you download gowall ( release?, git commit?) 

Also this exact config which i copy-pasted from your response yields an unmarshal yml error : 
If you just type `gowall` you should see this on the top, that means that you did not write valid yaml.
```
2025/02/13 10:36:23 error unmarshalling config file: yaml: unmarshal errors:
  line 12: cannot unmarshal !!str `false/` into bool
```

```yml
$ cat ~/.config/gowall/config.yml
themes:
  - name: "placeholder1"
    colors:
      - "#000000"
      - "#ef766d"
      - "#88f397"
      - "#f4f8a7"
      - "#c4a9f4"
      - "#aceafb"
      - "#ffffff"
      - "#f297cd"
EnableImagePreviewing: false/ <-- this causes an unmarshal error, remove the '/'
```

**Comment by CristolGDM** [comment]
@Achno Thanks for the fast answer!

Sorry for the `false/` I think it comes from my terminal, it's not there in the file itself:

```yaml
themes:
  - name: "placeholder1"
    colors:
      - "#000000"
      - "#ef766d"
      - "#88f397"
      - "#f4f8a7"
      - "#c4a9f4"
      - "#aceafb"
      - "#ffffff"
      - "#f297cd"
EnableImagePreviewing: false
```

I don't get the message you mentioned when running gowall

Regarding how I installed, I cloned the repo and then did `go build` inside the folder. I'm apparently at version v0.2.0
